### ISSUE TITLE
Games won't launch on custom wine since 1.2.1

### ISSUE THREAD

**Issue by clebercasali** [flavioislima/HeroicGamesLauncher#120]
It used to work fine up to 1.2.0.
Since 1.2.1, when I try to launch a game, wine tries to update the prefix, like the wine and prefix versions mismatch, and the game never launches.
Launching 'winecfg' from the setting menu works, though.

**Comment by flavioislima** [comment]
I put some observation on the 1.2.1 release:
`As in the previous version, if a game doesn't want to launch, try going to settings and changing the proton/wine version to update the settings due to some internal name changes.`

This is because I did some changes on the names. Just select another version and get back to the one you were using and the config will be updated.

**Comment by clebercasali** [comment]
Didn't work.
I've also tried to remove all config files from ~/.config/heroic and start over. Didn't work either.
Looks like it's trying to run either with the wrong wine or the wrong prefix.
![screen](https://user-images.githubusercontent.com/13246236/106180256-d5743800-617a-11eb-8b84-fd0965afb517.png)

Games will launch normally when I roll back to 1.2.0.

**Comment by flavioislima** [comment]
Can you run heroic from the terminal and check the logs?
Try to remove the folder `.config/heroic/tools` as well.

**Comment by clebercasali** [comment]
`launching Quail

 Launch Command:   /tmp/.mount_heroiccvtZCj/resources/app.asar.unpacked/build/bin/legendary launch Quail  --wine '/home/user/.local/share/lutris/runners/wine/wine-tkg/bin/wine64' --wine-prefix '/media/Dados/wine/wine-tkg/wineprefix' `
 
I had 'tools' and 'Tools'.
Removed both, and that did the trick. Thank you!

**Comment by flavioislima** [comment]
Nice!

I'll close then,

**Comment by clebercasali** [comment]
This happened again when I updated from1.3.1 to 1.4.0.
Changing to default wine and back to custom wine didn't work.
Deleting 'tools' and 'GamesConfig' didn't work either.
Changing it in game config didn't work either.
I got it to work again, but I'm not sure how.
I think I have changed wine in game config, chosen prefix directory again, closed heroic, changed all back again, closed heroic, opened heroic and launched the game it started to work again.
Something is still wrong.

**Comment by flavioislima** [comment]
Yeah, and this kind of bug is hard to reproduce. Before every release I test with both a clean install and my personal install of Heroic and legendary. I install some games, uninstall, play with proton, with wine, etc. Do test most of the features. But since we have so many distributions, with different kernels, config, etc. Is impossible to test all use cases.

At start I had several issues only on ubuntu. Then had others on open suse and others on Fedora, all different errors. 

At least you got it working then. 

Have you looked at the logs?

**Comment by clebercasali** [comment]
I think I have figured out what's going on.
It's trying to install dxvk in my custom prefix, but using vanilla wine, and that's what is breaking my custom prefix.

`$ ./heroic-1.3.1.AppImage 
launching 48619f5656da446abccb727b78cda644
GameMode not installed

 Launch Command:       /tmp/.mount_heroicbhwWmR/resources/app.asar.unpacked/build/bin/legendary launch 48619f5656da446abccb727b78cda644  --wine '/home/usuario/.local/share/lutris/runners/wine/wine-tkg/bin/wine64' --wine-prefix '/media/Dados/wine/wine-tkg/wineprefix' 


$ ./heroic-1.4.0.AppImage 
launching 48619f5656da446abccb727b78cda644
installing DXVK on '/media/Dados/wine/wine-tkg/wineprefix' WINEPREFIX='/media/Dados/wine/wine-tkg/wineprefix' bash /home/usuario/.config/heroic/tools/DXVK/dxvk-1.7.3L-03f11ba/setup_dxvk.sh install
GameMode not installed

 Launch Command:       /tmp/.mount_heroicrc1FJr/resources/app.asar.unpacked/build/bin/legendary launch 48619f5656da446abccb727b78cda644  --wine '/home/usuario/.local/share/lutris/runners/wine/wine-tkg/bin/wine64' --wine-prefix '/media/Dados/wine/wine-tkg/wineprefix'
`

In my opinion, dxvk installation should be optional, or heroic should at least ask before installing it.
Older GPUs don't have Vulkan at all, and there are a few games that run better with wined3d.

**Comment by clebercasali** [comment]
![screen](https://user-images.githubusercontent.com/13246236/108274684-fb767200-7153-11eb-8f55-24eaf8223cb3.png)

Got this again after updating from 1.4.0 to 1.5.1.
Weird as my wine prefix is NOT configured to "/home/user/.wine".
This is not really fixed.

**Comment by flavioislima** [comment]
There is a new option to disable auto install dxvk. Try disabling it. Also now the installation is done by winetricks instead of Heroic. But why the prefix is wrong thats weird. Is possible that the update might have broken your settings. Check if that's the case because 1.5 came with a lot of structural changes

**Comment by clebercasali** [comment]
I have disabled dxvk installation before trying to launch the game.
Still it tried to do something in the default wine prefix.
I'll roll back to 1.4.0 and then update to 1.5.1 again, to see if I can reproduce it and get a log.

**Comment by clebercasali** [comment]
I couldn't reproduce it.
Maybe it happens again next version (I hope not ;)

**Comment by flavioislima** [comment]
I think was something with the settings. 
The ideal would be to remove the .config/heroic folder but then you would lose your games config, but everything would be generated again, avoiding error.

**Comment by flavioislima** [comment]
@clebercasali found the issue thanks to #178

**Comment by clebercasali** [comment]
Awesome! Thank you!
