### ISSUE TITLE
cannot install/download new games from my account

### ISSUE THREAD

**Issue by FranGarc** [flavioislima/HeroicGamesLauncher#122]
Upgraded to 1.2.2, games didn't start. At first I thought maybe the games needed a reinstall, so I uninstalled one of them which I hadn't installed via heroic.  When two games I did have installed via heroic and I had played in the last few days also failed, I began looking for errors in the logs.

I found `SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25` and some googling led me to install winbind to fix it, but games still didn't work, so I tried uninstalling heroic and reinstalling the 1.2.0 version I had still in my Downloads folder.

Installed games now work, but now i cannot install/download new games from my account. I go into a game, push "install", "Installing" flashes for a few seconds and then it dissapears and the button goes back to "install". In "Downloading" there's nothing.

Any help would be appreciated.

**Comment by flavioislima** [comment]
I added this info on the 1.2.0 and 1.2.1 release:
`As in the previous version, if a game doesn't want to launch, try going to settings and changing the proton/wine version to update the settings due to some internal name changes.`

Probably this was the issue.
One tip: when launching fails, check the latest log going on the game page >  3 dots > Latest Log.
Install logs stay on `.config/heroic/GameConfig` folder.

Probably something happened with your authentication after you downgraded.
Try to remove the file: `.config/legendary/user.json` and restart heroic.
The login again.

In the worst scenario, delete both legendary and heroic folders on .config, login again and import your games.

**Comment by FranGarc** [comment]
It took a couple tries, but I got it to work again.
About the change in the proton/wine version: i always use the default, what should I change that to should I have future issues with updates?

**Comment by flavioislima** [comment]
@FranGarc I don't think I'll make this kind of change anymore but if I need I'll try to automate the migration of files and folders.

can we mark this as solved?

**Comment by FranGarc** [comment]
Yes, thanks!
