### ISSUE TITLE
saved games aren't saved inside a prefix but instead they are saved inside home/equivalent/folder

### ISSUE THREAD

**Issue by warriormaster12** [flavioislima/HeroicGamesLauncher#159]
**Describe the bug**
When creating a custom prefix for a game and playing for a couple of minutes, it saves files not inside the prefix folder but instead in the home directory equivalent

**To Reproduce**
1. select a game in heroic and go to game's launch settings and change prefix location
2. Launch the game and play it until you can save the game.

this is how the prefix looks like
![image](https://user-images.githubusercontent.com/33091666/108047162-28406180-704e-11eb-9293-ae06e9b63c62.png)

**Expected behavior**
this is how it should look like. The game should save to the prefix not "home/documents/MyGames/"
![image](https://user-images.githubusercontent.com/33091666/108047238-3db58b80-704e-11eb-86e5-403f37cf3a4d.png)

**Desktop (please complete the following information):**
 - OS: KDE Neon 20.04 lts
-  Game: Rocket League and Metro 2033 Redux 
-  Wine/Proton version: lutris 6.0 and lutris 5.21

**Comment by flavioislima** [comment]
Heroic does not have a config to select the save game folder. What it has is a config to set the Cloud sync save folder.
This means that heroic does not create those folders, but wine does.

If you go to the Prefix, you will be able to see that My Documents is a symbolic link to your Documents folder in home. So If a game create a save inside My Documents/My Games, etc. It will be on your documents folder.

I don't know if this is related to some wine changes recently, but I noticed this a while ago, even before starting working on heroic while using Lutris.
On the other hand, I think this doesn't happens with Proton since it creates a new user called steamuser.

But, the bottom line is that Heroic does not deal with save games, etc. Only those that are synced with the cloud and that's not the case for Metro 2033 and Rocket League.

**Comment by flavioislima** [comment]
Yeah, just tested with the default wine and this is the default wine behavior. To be honest for me this is most a feature than a bug. But I know some people doesn't like it and with winetricks you can setup a sandbox for wine to use and this might fix it. Otherwise, you can simple remove the links and recreate the folders.

To test it, just do something like this:
`WINEPREFIX=~wine-test winecfg`
you will see the symbolic links on the user folders on the new prefix.

**Comment by flavioislima** [comment]
As a matter of fact, Lutris wine has different behavior and it sandboxes the home folder by default. So the thing is that Heroic is using the default wine to install the DXVK so maybe that can be the issue. 🤔

**Comment by warriormaster12** [comment]
I see what you mean but honestly I would rather want it to behave like on lutris or steam than default 😅 because then I don't have to fill my ssd with saved games. So if it is possible to add sandboxing as a option, I'll take it.

**Comment by flavioislima** [comment]
> I see what you mean but honestly I would rather want it to behave like on lutris or steam than default  because then I don't have to fill my ssd with saved games. So if it is possible to add sandboxing as a option, I'll take it.

Yeah, I'll add as a new option under the wine settings.

**Comment by flavioislima** [comment]
@warriormaster12 forgot to say but I added this as a default bahavior when creating new prefixes with Wine. 
I'll think about adding a option to NOT have a sandbox folder. But for now this will be de default because I think is most safe and it is the default for Lutris as well and would be good to follow the same logic here 😄 
So I'll close the issue for now.

Thanks
