### ISSUE TITLE
"LibraryInstalledSettings" button

### ISSUE THREAD

**Issue by chernyaknikita** [flavioislima/HeroicGamesLauncher#16]
If you click "LibraryInstalledSettings" sign from any page
![image](https://user-images.githubusercontent.com/43153062/103492625-312df880-4e3d-11eb-92b0-ef12244e8432.png)
it'll show you this.
![image](https://user-images.githubusercontent.com/43153062/103492376-8f59dc00-4e3b-11eb-929c-07469977bcb8.png)
The problem is that you can't leave this page except you restart the app. Also the page is quite pointless coz it doesn't even show installed games (sign "Installed Games" isn't clickable).

**Comment by flavioislima** [comment]
HI!
This is happening because you're using a version that wasn't released. This version was just for testing the bug fix on the library loading.

This was just a test for the navbar but it is not ready.
This how is going to be:
https://github.com/flavioislima/HeroicGamesLauncher/pull/11#issuecomment-753611627

**Comment by flavioislima** [comment]
Use this version that is the one with the bugfixes and do not have this 'navbar' on top.
https://github.com/flavioislima/HeroicGamesLauncher/releases/tag/0.4.1-beta
