### ISSUE TITLE
Error when trying to install any game

### ISSUE THREAD

**Issue by jeisux92** [flavioislima/HeroicGamesLauncher#165]
The bug is happening when I click any game for downloading, It's showing this error "This game is not installed" and a modal saying "Game Imported", but I click again on Install and I get the bug again. I don't know if I am doing something wrong or is just a bug in the application, thanks guys  for your help

![image](https://user-images.githubusercontent.com/31553757/108158407-dd0c6a00-70b2-11eb-8902-ce205ae227da.png)

![image](https://user-images.githubusercontent.com/31553757/108158445-ec8bb300-70b2-11eb-889a-5126a30f4cf5.png)

**Comment by flavioislima** [comment]
Do you have disk space available? Currently heroic is not checking this so this might be the issue. Like on #156.
The default path is your home folder. 
Check this, otherwise run heroic from the terminal, when click on install it will show you the install command, copy it and paste it on a terminal and run to see the output.

**Comment by jeisux92** [comment]
Hi @flavioislima , yes I just tested it and it was because I didn't have enough space, thanks!
