### ISSUE TITLE
Heroic can't find proton in Ubuntu

### ISSUE THREAD

**Issue by Sebastian1978** [flavioislima/HeroicGamesLauncher#188]
Heroic can't find proton in Ubuntu.
Steam installed in Ubuntu via Software Centre with settings by default.
My proton folder is ".steam/steam/steamapps/common" but Heroic doesn't use this folder. 
It is default folder in Ubuntu.

Default folders in Heroic:
.config/heroic/Tools/wine
.config/heroic/Tools/proton
.local/share/Steam/compatibilitytools.d
.local/share/Steam/steamapps/common
.local/share/lutris/runners/wine
.var/app/com.valvesoftware.Steam (Steam Flatpak)
/usr/share/steam

You can see where is no right steam folder for Ubuntu

 - OS: [Ubuntu 20.10]
 - Version [1.5.3]
-  Game: 
-  Wine/Proton version:

**Comment by flavioislima** [comment]
If you check the full path, you will see that .steam is a symbolic link to .local/share/Steam.

Anyway. You can create a symbolic link from the proton folder to one of these folders to fix it.

**Comment by Sebastian1978** [comment]
@flavioislima I checked the full path. Folder .local/share/Steam contains only 1 directory userdata. It doesn't contain compatibilitytools.d or steamapps/common
As I know Steam previously used different directories in Ubuntu. It will be more convenient to user not to create symlinks by himself.
For example I don't use them and even don't know why and how create them

**Comment by flavioislima** [comment]
To be honest I think I should remove all those paths and keep only the one in Heroic folder so then everything would be in one place and this is a huge opportunity for you and others to learn something new that are the amazing Symbolic Links. Once you learn this, you will start using it everywhere 😛 

What do you think, @Sebastian1978 
?

**Comment by Sebastian1978** [comment]
@flavioislima as a programmer in the past I can tell that the program should be user-friendly. I don't think it will be user-friendly to force user to learn something;)

**Comment by flavioislima** [comment]
> @flavioislima as a programmer in the past I can tell that the program should be user-friendly. I don't think it will be user-friendly to force user to learn something;)

But learning is an amazing process.

I tried to implement your 'path', but the thing is that I have this issue:
On Manjaro and other distros, they have both paths:
`.local/share/Steam` and `.steam/steam` that is a symlink to the first one.

On my machine, if I add the second path, all Proton versions that are on the common folder get duplicated.
Since you're a developer, what do you think is the best approach:
- The first thing I tried was to use a Set instead of an Array since it filters duplicated automatically. But actually, the proton version arent duplicated since, even though the destination is the same, they have different paths.
- The second thing I thought was to check which path exists and use only one of them, but here is the deal: which one should I prefer? and also, this will work for all distros? Probably no because both paths exists on your machine, but only one has Proton installed.
- checking every path and check if it contains a string that has already in the array is possible, but it will be slow, and Heroic is checking for new wine/proton versions every time you open the wine settings. Also, the effort for that would be crazy.

So, as you can see, add one single path, at least in this case, can be challenging since Linux is quite a big world.

So, unfortunately, I'm not doing that. If you have an idea on how to do that, feel free to open and Pull Request here on the repository with the fix. 👍🏽
