### ISSUE TITLE
Import Game option, keeps loading endlessly

### ISSUE THREAD

**Issue by Peheux** [flavioislima/HeroicGamesLauncher#35]
I tried to import GTA V since I didn't want to reinstall it. Heroic kept loading enldessly. Once restarted Heroic tells the game is installed, but nothing happen once the game is started.

**Comment by flavioislima** [comment]
Hi! Can you try again on latest version? I tested now on 1.0.3 and it worked with no issues, after selecting import and clicking install, it takes a few seconds then reload the game page, tried to play the game and it worked as well. But I haven't tried GTA V, I tried Alien Isolation, Rime and Blair Witch, all of three worked fine.

On version 1.0.3 there is a option to check the latest play log, take a look and maybe it is not working because you're missing some dependency.

**Comment by Peheux** [comment]
Hello, thank you for your quick fix, it works nice now ! (except I didn't get my saves from the lutris installation automaticaly but that's not a big deal).
