### ISSUE TITLE
[Feature Request] Limit Bandwidth

### ISSUE THREAD

**Issue by VortexAcherontic** [flavioislima/HeroicGamesLauncher#40]
Hey there 👋🏿 ,

as the title already states. An option to limit the used bandwidth by the launcher would be nice.

Thank you in advance :)

**Comment by flavioislima** [comment]
Right now Legendary does not support it so I wouldn't be able to support on Heroic either since it uses Legandary to download the files: https://github.com/derrod/legendary/issues/132

One thing I can do is to add the option to set the max-workers like was said on the issue above. 

With time I'll add more of the Legendary options to Heroic and this one will be one of them.

**Comment by Translator5** [comment]
May using WonderShaper ?
