### ISSUE TITLE
Custom Wine builds

### ISSUE THREAD

**Issue by Ahmed-E-86** [flavioislima/HeroicGamesLauncher#47]
Under Defaul Wine Version I can only find Wine Default, and Proton GE. Is there a way to add custom Wine builds manually?

**Comment by flavioislima** [comment]
You can put Custom Proton on the `.steam/root/compatibilitytools.d` folder like you do for steam.
For custom Wine, the App looks on the Lutris folder since it is the most common. So you can drop your custom wine on:
`.local/share/runners/wine`

I'm planning to add a Custom Wine option as well in the future.

**Comment by Ahmed-E-86** [comment]
OK. Thanks.
