### ISSUE TITLE
proton on default wine prefix error

### ISSUE THREAD

**Issue by BlackMagik666** [flavioislima/HeroicGamesLauncher#57]
Hello everyone,

I just installed Heroic, this launcher is very good. I tried to launch Satisfactory and I get this error: "proton on default wine prefix ". The game doesn't launch. I try with Proton GE and Wine and I have the same result.

How to solves this issue ? Thanks

![ksnip_20210117-155107](https://user-images.githubusercontent.com/77579399/104847158-c1107f80-58de-11eb-889a-bd7e6f60f81f.png)

edit : i have this error with another game too.
edit 2 : I try this tutorial, doesn't work too (https://www.youtube.com/watch?v=vJjdi0AsrFg)

**Comment by flavioislima** [comment]
This is intentional, I added this message to avoid breaking your default wine prefix that should not use proton.
To avoid this error, go to the game settings and create a new wine prefix for it.
also, using the same prefix with games using proton and wine, can break your stuff, so keep them separate. You can have one prefix for all games that uses Wine and another one for all that uses Proton, but since some games needs special configs, you might need to have a prefix for some specific games.

**Comment by BlackMagik666** [comment]
ok thanks you it's working now.
