### ISSUE TITLE
Borderlands 2 don't start

### ISSUE THREAD

**Issue by LorenzoCesana** [flavioislima/HeroicGamesLauncher#77]
I installed HGL from AUR (heroic-games-launcher.bin 1.1.1-7) and installed Borderlands 2 but can't launch it

**Comment by flavioislima** [comment]
Hi!
We can't really support launching games here since every game needs specific configurations sometimes. You need to try with different  wine versions, etc. There is a "check compatibility" button that you can use to open ProtonDB and check the solutions there.

AFAIK, you need to rename the exe for borderlands 2, to call the game instead of the launcher.
