### ISSUE TITLE
Detect already running games

### ISSUE THREAD

**Issue by wiryfuture** [flavioislima/HeroicGamesLauncher#79]
It would be useful if the launcher could detect if a game is already open if you go into the launcher after the game was opened, so that you could press stop on the play button if the game stops responding or the wine config doesn't work and the launcher happened to be closed by accident after the game was launched.

If Legendary doesn't provide some way of getting this information, a primitive way of doing this would be to store a list of the games someone has installed from `legendary list-installed` and then check if there's any process with their name and use that to find out if a game is already running.

If no one else is interested in this I could take a look and try implement it myself sometime 🤷🏼‍♀

**Comment by flavioislima** [comment]
Yeah, this is implemented already but needs improvements.
In my current branch minor_tweaks I changed the handlePlaying function to be and object with the appName and the status, so with this I fix the bad behavior that sometimes the stop button was leading like discussed here on #31.

but it can be improved. The thing is that we can use the appName to store the information and kill the process, like I'm doing already with `pkill -f appName`, I dont think will make too much difference using the process name or the exe for instance. Since Pkill -f will kill anything that contains the appName on it, and it will always have since the legendary process calls for it.
