### ISSUE TITLE
Controller support on Proton

### ISSUE THREAD

**Issue by paulopaim** [flavioislima/HeroicGamesLauncher#97]
Hello again!

If possible, could you verify the controller support with Proton? the game starts fine, but without controller support (like Xbox controller).

I tested with my two games (using Proton 5.0):

- Overcooked
- Rocket League

I tried to choose Proton experimental and 5.13 versions, but the games won't run with these versions.

**Comment by flavioislima** [comment]
there is not much to do since this is a known proton issue. 
Proton was made by valve to be used inside steam. Even though it works most of the time outside Steam, i have issues and sometimes can even corrupt saves, prefixes, etc. 

I support Proton on Heroic because most people asked for it and it will work on 90% of cases, but I strongly recommend using Wine versions like Lutris Wine. 

In the future I'll try to implement a way of downloading recommend wine versions on Heroic.

**Comment by flavioislima** [comment]
@paulopaim do you have a list of games that doesn't work with a controller? because I tried the xbox one controler with several games like Borderlands 2, GTA V, Control and they worked fine.

**Comment by paulopaim** [comment]
Hello!

I update the app and now it's working normally! :D

Thanks!

**Comment by kokoko3k** [comment]
What do you updated exactly?
I'm still having problems with proton and the controller.
Thanks.
